### ISSUE TITLE
Labeling of Mobile Chrome/Android Data May Give Faulty Impression

### ISSUE THREAD

**Issue by jpmedley** [epistemex/mdncomp#1]
Congratulations on a nice bit of work. I'll be using it frequently. 

I'm concerned that labeling the Chromium Android data as "Android" and "Chrome" will give a false impression. Calling Android Webview simply Android gives the impression of an Android-specific browser, which it is not. Referring to Chrome as Chrome for Android is not me being picky. Chrome on iOS is only Google's user interface, the engine is the iOS webview.

**Comment by epistemex** [comment]
Hi and thanks for the feedback! 

I hear you... How about I do something like this by extending the line a bit (max 72; and the 2 char indent can be removed if needed):

      MOBILE
      Webview/A | Chrome/A  | Edge      | Firefox/A | Opera/A   | Safari/iOS
      ----------+-----------+-----------+-----------+-----------+------------

**Comment by jpmedley** [comment]
Sounds good.

**Comment by epistemex** [comment]
Updated. Should be available from npm in an instance.
