### ISSUE TITLE
Unable to create config folder

### ISSUE THREAD

**Issue by rognstadragnar** [epistemex/mdncomp#6]
After installing using `npm i -g mdncomp` I get an error when running any commands, including the examples in the readme. 

```
Could not create config folder:
/Users/userLibrary/Preferences/mdncomp
ENOENT: no such file or directory, mkdir '/Users/userLibrary/Preferences/mdncomp'

Could not detect user data area on this system for config file!
Please report to: https://github.com/epistemex/mdncomp/issues
and include the following data (replace username with just user):
  Unresolved path: '/Users/userLibrary/Preferences'
  OS: 'darwin' + the path you would normally use for user data.
  APPDATA: undefined
  HOME: /Users/user
```

Note: there is no slash in the paths after my username

**Comment by epistemex** [comment]
Hi and thanks for reporting. Will issue a hotfix for this.

**Comment by epistemex** [comment]
Version 1.14.0-alpha released which (hopefully) resolves this issue. Please let us know how it goes.

**Comment by Jamesernator** [comment]
I'm having similar issues on 1.14.0-alpha:

```
Could not create config folder:
/var/local/mdncomp
EACCES: permission denied, mkdir '/var/local/mdncomp'
```

It'd probably be better if it used the `~/.mdncomp` scheme on linux so that it's a per user config directory.

**Comment by epistemex** [comment]
> It'd probably be better if it used the ~/.mdncomp/ scheme on linux so that it's a per user config directory.

Thanks @Jamesernator , that seem to a better approach. Will update.

**Comment by epistemex** [comment]
Thanks @Jamesernator, I see that I have hardcoded that path for linux; (I only got to Node's env.HOME overlooking the last part in the code). I will update also for this.

**Comment by epistemex** [comment]
OK, published a hotfix (1.14.1-alpha). I'm without darwin/linux VM atm but I think this workaround should work, at least allow the main purpose of the program. If you use the option "--configpath" it will show what it thinks is the path, if this works (or not) I would very much appreciate if you would let me know.

**Comment by Jamesernator** [comment]
The path given was `/home/jamesernator/mdncomp` although I think it would be preferable if it were placed in a hidden folder instead so that it doesn't add a folder that's seen in the file viewer. e.g. `/home/jamesernator/.mdncomp` or even `/home/jamesernator/.config/mdncomp`.

**Comment by epistemex** [comment]
Folders are now created in HOME directory (incl. on Windows, i.e. c:\users\-user\) and as sub-folder starting with dot ".mdncomp". The config file is now expected to be .config.json.

**Comment by epistemex** [comment]
@Jamesernator  my bad, I should really not do updates past bedtime. I forgot to update for --configpath after moving the config folder end-path to a different part... :-/ I have in any case refactored the config path internals. I landed on using .mdncomp rather than .config to avoid possible conflicts (and perhaps for portability). And thanks for testing btw! I seem to work in the Linux VM (Ubuntu) I am testing with. I hope this also solves for @rognstadragnar as well.
